# Generated by Django 2.2.3 on 2019-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_approvals_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='license_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='picture',
            field=models.CharField(max_length=200),
        ),
    ]
