# Generated by Django 2.2.3 on 2019-07-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20190729_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='chat_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
